// var par = document.getElementById('body');
// alert(par[0].innerHTML);
// var textInMiddleParagraph = par[1].innerHTML;
// alert(textInMiddleParagraph);
// par[1].innerHTML = "This SUV is too big.";
// var v = par[1].nodeType;
// alert(v);
// var d = document.getElementById("div2");
// var p = d.childNodes[1];
// var contents = p.innerHTML;
// var nType = d.nodeType;
// alert(contents);
// alert(nType);
// var kidNode = document.getElementById("div2");
// var pNode = kidNode.parentNode;
// alert(pNode);
// var firstEl = document.getElementById("div2");
// var secondEl = firstEl.nextSibling;
// alert(secondEl);
// var parent = document.getElementById("div2");
// var target = parent.firstChild;
// var nName = target.nodeValue;
// alert(nName);
// var a = document.getElementsByTagName('p')[0].innerHTML;
// alert(a);
// var target = document.getElementById("div2");
// var attVal = target.getAttribute("class");
// alert(attVal);
// var list = document.getElementsByTagName("p");
var parentDiv = document.getElementById("div2");
var newParagraph = document.createElement("p");
var t = document.createTextNode("Hello world!");
newParagraph.appendChild(t);
var paragraph1 = parentDiv.firstChild;
// parentDiv.insertBefore(newParagraph, paragraph1);
var target = parentDiv.childNodes[3];
parentDiv.insertBefore(newParagraph, target.nextSibling);