// alert("Please enter a valid password");
// alert("Wellcome to JS Land \n Happy Coding!");
// var username;
// var myName = "Mansoor Hussain"
// alert(myName);
// var message = "Hello world";
// alert(message);
// var lunch = "PIZZA";
// alert(lunch);
// lunch = "PIZZ";
// alert(lunch);
// lunch = "PIZ";
// alert(lunch);
// lunch = "PI";
// alert(lunch);
// lunch = "P";
// alert(lunch);
// alert("PIZZA \n PIZZ \n PIZ \n PI \n P");
// var email = "hussainmansoor876@gmail.com";
// alert("My email addres is: "+email);
// document.write("<h1>Yay! I can write HTML content through Javascript</h1>");
// var age = 28;
// alert("I am "+age+" years old");
// var N = 21;
// alert("You have visited this site "+N+" times.");
// var visitorName = "Mansoor Hussain",quantity = 3 , product = "XYZ";
// alert(visitorName+" "+quantity+" "+product);
// document.write("<h1>Value after declaration is:??");
// var num = 3;
// document.write("<br>Initial value:"+num);
// num = num+1;
// document.write("<br>After increament value is:"+num);
// num = num+7;
// document.write("<br>Value after addition is:"+num);
// num = num-1;
// document.write("<br>Value after decreament is:"+num);
// num = num%3;
// document.write("<br>The remainder is:"+num+"</h1>");
// var celsius = 56;
// var f=(celsius*9/5)+32;
// document.write(celsius+"<sup>o</sup>C is "+f+"<sup>o</sup>F<br>");
// celsius=(f-32)*5/9;
// document.write(f+"<sup>o</sup>F is "+celsius+"<sup>o</sup>C");
// var a = (1,5-1)*2;
// document.write(a);